version: "3.3"
services:
  db_postgres:
    container_name: db_postgres_app
    build: ./db/
    ports: 
      - 5433:5432

  solr_app:
    image: solr:8
    container_name: solr_app
    environment:
      - SOLR_JAVA_MEM=-Xms4g -Xmx4g
    volumes:
      - ./solrdata:/opt/solr/server/solr/configsets/
    ports:
      - 8983:8983
  
  processing_engine:
    build: ./processing_engine/
    container_name: processing_engine_app
    volumes:
      - "./processing_engine:/processing_engine/"
    links: 
      - db_postgres
    depends_on:
      - db_postgres
  
  api_search_engine:
    build: ./api_search_engine/
    container_name: api_search_engine_app
    volumes:
      - "./api_search_engine:/api_search_engine/"
    ports: 
      - 5000:5000
    links: 
      - db_postgres
      - solr_app
    depends_on:
      - db_postgres
      - solr_app

  search_app:
    build: ./search-app/
    container_name: app_search
    volumes:
      - "./search-app:/usr/src/app/"
    ports:
      - 80:80
    links:
      - api_search_engine
    depends_on:
      - api_search_engine