version: "3.3"
services:
  db_postgres:
    build: ./db/
    ports: 
      - 5433:5432

  solr_app:
    image: solr:8
    volumes:
      - ./solrdata:/opt/solr/server/solr/configsets/
    ports:
      - 8983:8983
  
  api_search_engine:
    build: ./api_search_engine/
    ports: 
      - 5000:5000
    links: 
      - db_postgres
      - solr_app
    depends_on:
      - db_postgres
      - solr_app